on:
  - pull_request
  - push
  - release
jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        watcom_version:
          - "1.9"
          - "2.0"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: madebr/setup-watcom@0.0.2
        with:
          version: "${{ matrix.watcom_version }}"
      - name: Build system information
        run: |
          cmake --version
      - name: Build real DOS executable
        run: |
          cmake -S . -B build_dos_real "-DCMAKE_TOOLCHAIN_FILE=cmake/watcom-DOS-real.cmake"
          cmake --build build_dos_real
          cmake --build build_dos_real --target package
      - name: Build protected DOS executable
        run: |
          cmake -S . -B build_dos_protected "-DCMAKE_TOOLCHAIN_FILE=cmake/watcom-DOS-protected.cmake"
          cmake --build build_dos_protected
          cmake --build build_dos_protected --target package
      - name: Build for Windows
        run: |
          cmake -S . -B build_windows "-DCMAKE_TOOLCHAIN_FILE=cmake/watcom-Windows.cmake"
          cmake --build build_windows --verbose
          cmake --build build_windows --target package
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
            name: action-artifact
            if-no-files-found: error
            path: |
                **/*.zip
