on:
  - pull_request
  - push
  - release
jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: madebr/setup-watcom@0.0.1
      - name: Build system information
        run: |
          cmake --version
      - name: Build for DOS
        run: |
          cmake -S . -B build_dos -DCMAKE_TOOLCHAIN_FILE=cmake/watcom-DOS.cmake -G "Watcom WMake"
          cmake --build build_dos
      - name: Build for Windows
        run: |
          cmake -S . -B build_windows -DCMAKE_TOOLCHAIN_FILE=cmake/watcom-Windows.cmake -G "Watcom WMake"
          cmake --build build_windows --verbose
